project:
  type: website

website:
  title: "CogModWeb"
  cookie-consent: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - pubs.qmd

  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

editor: visual

